const WorkExperience = [
    {
        id: 1,
        title: "Technical Leader",
        company: "Quality IT",
        yearsActive: "May 2021 - Present",
        information: [
            "Led and participated in the development of various web and mobile apps including Lemonade, Thinknum, and AELER using cutting-edge technologies, including React, React Native, Next.js, Node.js, Nest, Golang, Python, and Ruby on Rails.",
            "Implemented high-performance REST APIs endpoints for AELER and Thinknum using Node.js, Nest, PostgreSQL, Supabase and Prisma.",
            "Developed pixel-perfect web and mobile frontend of Thinknum and Lemonade which processes visual data and model using TypeScript, Next, React Query, Recoil, Shadcn, Styled Component and Tailwind CSS.",
            "Utilized RabbitMQ in AELER project to manage and streamline real-time messaging and communication between microservices, enhancing the efficiency and reliability of data processing and transportation logistics.",
            "Developed features for Lemonade app using Flutter, implementing policy management, claims tracking, and user notifications to enhance functionality and user experience on iOS and Android platforms.",
            "Developed an AI chatbot for Lemonade admin panel by integrating Dialogflow and OpenAI within the Nest.js backend service, enhancing administrative efficiency and support capabilities.",
            "Strong background in cloud services, including AWS, GCP, Docker and Kubernetes, proficient in designing and implementing cloud architectures, deploying and managing applications.",
            "Led a team of 7 members while performing code reviews, scrum planning, mentoring, and providing technical leadership and guidance.",
        ],
    },
    {
        id: 2,
        title: "Senior Software Engineer",
        company: "QuinnBet",
        yearsActive: "Oct 2019 - Apr 2021",
        information: [
            "Built a web application from scratch for streamers and viewers to manage challenges and donations, integrating with Streamlabs and OBS using JavaScript, Angular, Angular Material, NgRx, SCSS, HTML, Node.js, and DigitalOcean.",
            "Led the migration of an Angular project to Next and deployed it on Vercel, enhancing SEO with built-in optimization features, implemented SSR and SSG for faster load times and better performance, improving user experience and content delivery.",
            "Transitioned UI components from Angular Material to TailwindCSS, Radix UI and Styled Components, achieving a 40% reduction in component loading speed and providing a modern and consistent look and feel.",
            "Enhanced the Nest.js backend service architecture by updating RESTful APIs to GraphQL and integrating AWS SQS, managing application performance effectively and improving data handling.",
            "Worked with a comprehensive tech stacks, including Firebase, GraphQL, Apollo Server/Client, TypeScript, NextAuth, Redux, Zod, Yup, React Query, tRPC and microservices architecture.",
            "Led the creation of a Web3-based sports betting pages integrating blockchain technologies, using Ethereum smart contract, Solidity, and Web3.js for secure transactions and betting logic. Enhanced user experience with NextJS and Node.js for seamless interaction.",
            "Developed and executed unit testing, integration testing, and end-to-end testing using Jest, Cypress, and Mocha+Chai, ensuring highquality code and application performance while collaborating closely with the Quality Assurance (QA) team for comprehensive test coverage.",
            "Leveraged AWS services such as EC2, S3, Lambda, RDS, and SQS for deployment and optimization, ensuring robust, scalable, and highperformance application infrastructure.",
            "Mentored junior team members in advanced development principles and best practices, fostering their growth and improving team efficiency.",
        ],
    },
    {
        id: 3,
        title: "Software Engineer",
        company: "Swinton Insurance",
        yearsActive: "Apr 2016 - Sep 2019",
        information: [
            "Led the design and implementation of homeowners, property and life insurance underwriting software, which streamlined risk assessment processes and reduced underwriting time by 30%, enhancing client satisfaction and throughput.",
            "Spearheaded the implementation of API integration with multiple insurance carriers, enhancing quick quoting features that reduced quote generation time by 30% for agents.",
            "Collaborated with data engineering teams to develop an AI-driven tool using satellite imagery analysis, improving wildfire risk assessments by 40% and supporting underwriting decisions and implementing a powerful search feature using Elasticsearch for real-time .",
            "Led the development and integration of online signature capabilities using Dropbox Sign, achieving a 35% increase in document processing speed and enhancing customer experience.",
            "Implemented a seamless integration with Ivans to automate data exchanges, which enhanced data accuracy by 20% and reduced manual data entry by 50%.",
            "Tech stack - API Integration, SSO, OKTA, Auth0, Node, Nest, TypeScript, Next, Restful API, Relational Databases, Postgres, Supabase,Sequelize, Training Programs, Build Tools, Stripe, PayPal, Docker, Kubernetes, Shell Scripting.",
        ],
    },
    {
        id: 4,
        title: "Software Engineer",
        company: "Miquido",
        yearsActive: "Apr 2014 - May 2016",
        information: [
            "Collaborated with a cross-functional team to design and develop an education website and mobile application from scratch, utilizing a tech stack that includes Python, Django, PostgreSQL, SQLAlchemy, React.js, Vue.js and React Native and deployed the entire solution on AWS.",
            "Designed and implemented RESTful APIs using Python, Django, and Django Rest Framework, ensuring robust and scalable back-end services, utilizing SQLAlchemy for efficient ORM (Object-Relational Mapping) and database interactions with PostgreSQL.",
            "Designed a scalable micro-service architecture for front-end, ensured seamless RESTful API communication, utilized Docker containers for deployment, used Nginx for routing and load balancing, and set up CI/CD pipelines with Jenkins.for automated testing and deployment.",
            "Developed dynamic and responsive user interfaces using React, ES6, React Router for navigation, Redux for state management, MUI for design components, Webpack for bundling, Axios for HTTP requests, ESLint for code quality, and Babel for cross-browser compatibility.",
            "Built admin panel components using Vue with two-way data binding, Vue Router for routing, Vuetify for design, and Gulp for automation.",
            "Developed a mobile app for iOS and Android with push notifications for timely updates, offline access for uninterrupted learning, real-time updates for dynamic content, interactive quizzes, progress tracking, and a user-friendly interface to enhance the overall learning experience.",
            "Deployed the application on AWS Services using EC2, CloudFront, S3, SNS, Lambda, API Gateway, and RDS, implementing a Serverless Architecture with CI/CD pipelines via CodePipeline and CodeDeploy, and monitoring with CloudWatch for performance and reliability.",
        ],
    },
    {
        id: 5,
        title: "Full Stack Engineer",
        company: "Huma",
        yearsActive: "Apr 2012 - Mar 2014",
        information: [
            "Developed and maintained a health web application, migrating an education web application from the LAMP stack app to MERN stack app.",
            "Translated redesigned Figma designs to pixel-perfect and fully responsive web application using JavaScript, React, SASS and LESS.",
            "Rebuilt backend services in Node.js using Express.js, creating RESTful APIs to handle various insurance operations such as policy management, claims processing, and user management.",
            "Migrated data from MySQL to MongoDB, optimizing data models and queries to take full advantage of MongoDB’s performance capabilities.",
            "Implemented secure authentication flow using JWT (JSON Web Tokens) to ensure safe and efficient user authentication and authorization.",
            "Integrated third-party services and APIs to provide additional functionality, such as payment processing and real-time notifications using Stripe, PayPal and WebSockets technologies.",
            "Set up Continuous Integration/Continuous Deployment pipelines (CI/CD) using GitHub Actions to automate testing and deployment, ensuring rapid and reliable delivery of new features and updates.",
        ],
    },
    {
        id: 6,
        title: "Software Developer",
        company: "Softwire",
        yearsActive: "Sep 2010 - Mar 2012",
        information: [
            "Transformed design mock-ups into HTML5/CSS3 layouts and created Responsive Web libraries by utilizing the main styling tools and stuff and enhancing UI/UX Design in agile development team.",
            "Participated in development of Ecommerce and CRM systems with CMS systems including Drupal, WordPress, Joomla and OOP, MVC structure, Laravel, SQL,Git and followed Pixel Perfect design and implementation.",
            "Involved in writing application level code to interact with APIs, Web Services using AJAX, JSON and XML.",
            "Used jQuery for basic animation and end user screen customization purposes.",
            "Collaborated closely with senior developers to troubleshoot bugs, perform code review and debugging, and implement performance enhancements, contributing to the app's reliability, stability, and overall efficiency.",
        ],
    },
];

export default WorkExperience;
